apiVersion: 1

datasources:
- name: Loki
  type: loki
  typeName: Loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  readOnly: false
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: false
  access: proxy
  editable: true
