postgres:
  url: $POSTGRES_URL
chains:
  polygon:
    rpc: $POLYGON_RPC_URL
    contracts:
      link:
        abi: "LINK.abi"
        addresses:
          - "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
