chains:
  eth_mainnet:
    rpc: $ETH_MAINNET_RPC_URL
    contracts:
      usdc:
        abi: "ERC20.abi"
        address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
        events:
          - "Transfer"
      link:
        abi: "ERC20.abi"
        address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
  polygon:
    rpc: $POLYGON_RPC_URL
    contracts:
      usdc:
        abi: "ERC20.abi"
        address: "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
        events:
          - "Transfer"
      link:
        abi: "ERC20.abi"
        address: "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
outputs:
  postgres:
    url: $POSTGRES_URL
    retention: "1h"